### ISSUE TITLE
Duration formatter returns wrong value

### ISSUE THREAD

**Issue by bilinguliar** [dogtools/dog#119]
Hi, 
Looks like `formatDuration` function in chain.go returns incorrect result. Seems like each time unit represents the whole duration in some cases. This is reproducible via unit test in PR: https://github.com/dogtools/dog/pull/118

```
--- FAIL: TestFormatDurationReturnsProperlyFormattedString (0.00s)
	chain_test.go:46: Got time string: "26h1560m93599s", but expected: "25h59m59s"
	chain_test.go:46: Got time string: "1h70m4200s", but expected: "1h10m"
```
I can see few options to fix this, but the most obvious is to use standard [Duration.String()](https://golang.org/src/time/time.go?s=14992:15025#L448) method, that is pretty smart.

**Comment by xsb** [comment]
@bilinguliar I agree that using Duration.String() makes more sense that trying to implement our own duration formatter.

I [changed it](https://github.com/dogtools/dog/commit/47d5ad0aec78e5206f355e7a8373b4b048076461) and then tried running your test in #118, the output is:

```
--- FAIL: TestFormatDurationReturnsProperlyFormattedString (0.00s)
	chain_test.go:46: Got time string: "1h10m0s", but expected: "1h10m"
	chain_test.go:46: Got time string: "1.5s", but expected: "2s"
	chain_test.go:46: Got time string: "1.001s", but expected: "1s"
	chain_test.go:46: Got time string: "1ms", but expected: "0.001s"
	chain_test.go:46: Got time string: "200ns", but expected: "0.000s"
```

The values provided by the time package are more precise and look better than the ones by the old formatDuration function.

I am going to close your PR as the test obviously don't pass (the expected output changed) and the behaviour is now covered by the standard library, thank you very much for your contribution.

**Comment by bilinguliar** [comment]
@xsb Thanks, I have created test based on your implementation expectations. We were able to eliminate the problem, so everyone is happy.
Cheers.
