### ISSUE TITLE
Pass data between tasks (aka registers)

### ISSUE THREAD

**Issue by xsb** [dogtools/dog#24]
I find the idea of [registers](https://github.com/xsb/dog/blob/master/DOGFILE_SPEC.md#register) interesting but at the same time it's confusing in it's current iteration.

- Do you think registers are a good idea?

- Do you think *register* is a good name for them?

- Can you think of other ways we could provide global variables/data without adding new objects into Dogfile's YAML root object?

**Comment by jcchavezs** [comment]
IMO, the name ``register`` is not meaningful. I think ``input`` would inside the task would be much explainatory. Even better, more than one input can be passed so the ``input`` can be a list and can be passed as parameters to the tasks. Makes sense?

**Comment by xsb** [comment]
After talking with @marc-gr I think we get an idea on how to implement this in the most simple way:

Idea:

- Registers are environment, their lifecycle starts and ends with Dog task-chain execution
- A task with a register directive will collect its STDOUT and inject it as a string in the named register (as in `register: FOO`)
- The following tasks in the chain (the ones that are defined as post-hooks or the ones that have the previous task as a pre-hook) will have access to environment variable created by the register.

This introduces even more complexity on environment variables inside Dog in general. So I think we should define and document env vars' order of precedence on Dog execution:

- Value from the system
- Default value defined in Dogfile (`env: RANDOM=42`)
- Value coming from the CLI (`-e RANDOM=18`)
- Value coming from a Register

**Comment by xsb** [comment]
I am closing this discussion, follow up in the issue #88
