### ISSUE TITLE
Accept Dogfiles in JSON

### ISSUE THREAD

**Issue by xsb** [dogtools/dog#26]
YAML is a superset of JSON, so any Dogfile written in JSON should be valid, we should support even Dogfiles mixing JSON and YAML

**Comment by aeony** [comment]
Can you think of a case where someone might want to mix up `json` and `yml`?

**Comment by xsb** [comment]
@aeony Dog accepts multiple dogfiles in the same directory and treats them as a single Dogfile, imagine for example:

```
$ ls -1 Dogfile*
Dogfile.json
Dogfile.yml
```

In which Dogfile.yml was written by a human and Dogfile.json was written by *a machine*. In that case when typing `dog` from that directory the following happens (current implementation):

- Dog reads every Dogfile in the current directory
- All Dogfiles are concatenated and provided to the parser as a single YAML object
- The parser treats them as a single Dogfile and matches all the tasks with our Task struct

As you see in this example no one is writing a mix of YAML and JSON but the parser receives a mix of them. In my opinion this makes a lot of sense because YAML is a superset of JSON, that should simply work.

Even if we don't menction that JSON is supported, people could write parts of a task in JSON and the YAML parser should understand it because it's valid YAML. I like how Kubernetes does it, they even provide examples in both YAML and JSON formats.

We still have to investigate why this doesn't work out of the box.
