### ISSUE TITLE
Improve parser to detect errors and provide line

### ISSUE THREAD

**Issue by marc-gr** [dogtools/dog#46]
What do you think about improving the parser to provide line debugging if encounters some error?

**Comment by xsb** [comment]
We can live with what we have for a while but It's a super good idea, definitely something we need if we want people to create Dogfiles :)

**Comment by slapresta** [comment]
It should probably complain when it finds things it doesn't understand, to prevent misspellings and the like.

**Comment by xsb** [comment]
This issue has been closed together with other old issues as part of a cleanup process.

Feel free to reopen or reference it if necessary.
