### ISSUE TITLE
Check that task name have no spaces in it

### ISSUE THREAD

**Issue by xsb** [dogtools/dog#67]
The [Dogfile Spec](https://github.com/dogtools/dog/blob/master/DOGFILE_SPEC.md) defines a task name as

> a string made of lowercase characters (a-z), may contain hyphens (-)

Why do we want to add a restriction like this? Because enforcing restrictions allows us to make assumptions in the future, and those assumptions simplify the creation of more tooling. If we know that task names have no spaces, other tools can assume that from the start.

I'm not 100% sure about enforcing lowercase but I like it, and while I think it's not super necessary for a cli, it is an obvious choise for other dogtools.

**Comment by aeony** [comment]
WIP!
