### ISSUE TITLE
Fail when directive name unrecognized

### ISSUE THREAD

**Issue by xsb** [dogtools/dog#70]
From the [Dogfile Spec](https://github.com/dogtools/dog/blob/master/DOGFILE_SPEC.md):

> Tools using Dogfiles and having special requirements can use their own directives that will be ignored by the tools that only follow the standard. Any parameter starting by x_ will simply be ignored.

Dog needs to actively ignore any directive starting with `x_` but at the same time fail if directive not in (task, description, run, exec, pre, post, workdir, env)

**Comment by aeony** [comment]
WIP

**Comment by xsb** [comment]
This issue has been closed together with other old issues as part of a cleanup process.

Feel free to reopen or reference it if necessary.
